
.entry: {
             ;objs            enemies          bounds,bg;   special ptr
    ..0:  dw room_objlist_0,  room_enemylist_0,  $c204,     $ffff
    ..1:  dw room_objlist_1,  room_enemylist_1,  $c004,     $ffff
    ..2:  dw room_objlist_2,  room_enemylist_2,  $c104,     $ffff
    ..3:  dw room_objlist_3,  room_enemylist_3,  $c304,     $ffff
    ..4:  dw room_objlist_4,  room_enemylist_4,  $c20a,     $ffff
    ..5:  dw room_objlist_5,  room_enemylist_5,  $c00a,     $ffff
    ..6:  dw room_objlist_6,  room_enemylist_6,  $c00a,     $ffff
    ..7:  dw room_objlist_7,  room_enemylist_7,  $c00a,     $ffff
    ..8:  dw room_objlist_8,  room_enemylist_8,  $c00a,     $ffff
    ..9:  dw room_objlist_9,  room_enemylist_9,  $c00a,     $ffff
    ..a:  dw room_objlist_a,  room_enemylist_a,  $c00a,     $ffff
    ..b:  dw room_objlist_b,  room_enemylist_b,  $c00a,     $ffff
    ..c:  dw room_objlist_c,  room_enemylist_c,  $c20a,     $ffff   ;
    ..d:  dw room_objlist_d,  room_enemylist_d,  $c00a,     $ffff
    ..e:  dw room_objlist_e,  room_enemylist_e,  $c00a,     $ffff
    ..f:  dw room_objlist_f,  room_enemylist_f,  $c00a,     $ffff
    ..10: dw room_objlist_10, room_enemylist_10, $c00a,     $ffff
    ..11: dw room_objlist_11, room_enemylist_11, $c00a,     $ffff
    ..12: dw room_objlist_12, room_enemylist_12, $c00a,     $ffff
    ..13: dw room_objlist_13, room_enemylist_13, $c10a,     $ffff   ;
    ..14: dw room_objlist_14, room_enemylist_14, $c102,     $ffff
    ..15: dw room_objlist_15, room_enemylist_15, $c102,     $ffff
    ..16: dw room_objlist_16, room_enemylist_16, $c102,     $ffff
    ..17: dw room_objlist_17, room_enemylist_17, $c102,     $ffff
    ..18: dw room_objlist_18, room_enemylist_18, $c102,     $ffff
    ..19: dw room_objlist_19, room_enemylist_19, $c102,     $ffff
    ..1a: dw room_objlist_1a, room_enemylist_1a, $c102,     $ffff
    ..1b: dw room_objlist_1b, room_enemylist_1b, $c102,     $ffff
    ..1c: dw room_objlist_1c, room_enemylist_1c, $c102,     $ffff
    ..1d: dw room_objlist_1d, room_enemylist_1d, $c102,     $ffff
    ..1e: dw room_objlist_1e, room_enemylist_1e, $c102,     $ffff
    ..1f: dw room_objlist_1f, room_enemylist_1f, $c102,     $ffff
             ;objs            enemies          bounds,bg;   special ptr
    ..20: dw room_objlist_20, room_enemylist_20, $c202,     $ffff
    ..21: dw room_objlist_21, room_enemylist_21, $c003,     $ffff
    ..22: dw room_objlist_22, room_enemylist_22, $c003,     $ffff
    ..23: dw room_objlist_23, room_enemylist_23, $c003,     $ffff
    ..24: dw room_objlist_24, room_enemylist_24, $c003,     $ffff
    ..25: dw room_objlist_25, room_enemylist_25, $c102,     $ffff
    ..26: dw room_objlist_26, room_enemylist_26, $c102,     $ffff
    ..27: dw room_objlist_27, room_enemylist_27, $c102,     $ffff
    ..28: dw room_objlist_28, room_enemylist_28, $c102,     $ffff
    ..29: dw room_objlist_29, room_enemylist_29, $c102,     $ffff
    ..2a: dw room_objlist_2a, room_enemylist_2a, $c102,     $ffff
    ..2b: dw room_objlist_2b, room_enemylist_2b, $c102,     $ffff
    ..2c: dw room_objlist_2c, room_enemylist_2c, $c102,     $ffff
    ..2d: dw room_objlist_2d, room_enemylist_2d, $c102,     $ffff
    ..2e: dw room_objlist_2e, room_enemylist_2e, $c102,     $ffff
    ..2f: dw room_objlist_2f, room_enemylist_2f, $c102,     $ffff
    ..30: dw room_objlist_30, room_enemylist_30, $c203,     $ffff
    ..31: dw room_objlist_31, room_enemylist_31, $c003,     $ffff
    ..32: dw room_objlist_32, room_enemylist_32, $c10a,     $ffff
    ..33: dw room_objlist_33, room_enemylist_33, $c10a,     $ffff
    ..34: dw room_objlist_34, room_enemylist_34, $c10a,     $ffff
    ..35: dw room_objlist_35, room_enemylist_35, $c10a,     $ffff
    ..36: dw room_objlist_36, room_enemylist_36, $c10a,     $ffff
    ..37: dw room_objlist_37, room_enemylist_37, $c10a,     $ffff
    ..38: dw room_objlist_38, room_enemylist_38, $c102,     $ffff
    ..39: dw room_objlist_39, room_enemylist_39, $c102,     $ffff
    ..3a: dw room_objlist_3a, room_enemylist_3a, $c102,     $ffff
    ..3b: dw room_objlist_3b, room_enemylist_3b, $c102,     $ffff
    ..3c: dw room_objlist_3c, room_enemylist_3c, $c102,     $ffff
    ..3d: dw room_objlist_3d, room_enemylist_3d, $c102,     $ffff
    ..3e: dw room_objlist_3e, room_enemylist_3e, $c102,     $ffff
    ..3f: dw room_objlist_3f, room_enemylist_3f, $c102,     $ffff
             ;objs            enemies          bounds,bg;   special ptr
    ..40: dw room_objlist_40, room_enemylist_40, $c203,     $ffff
    ..41: dw room_objlist_41, room_enemylist_41, $c003,     $ffff
    ..42: dw room_objlist_42, room_enemylist_42, $c202,     $ffff
    ..43: dw room_objlist_43, room_enemylist_43, $c002,     $ffff
    ..44: dw room_objlist_44, room_enemylist_44, $c002,     $ffff
    ..45: dw room_objlist_45, room_enemylist_45, $c107,     $ffff
    ..46: dw room_objlist_46, room_enemylist_46, $c102,     $ffff
    ..47: dw room_objlist_47, room_enemylist_47, $c102,     $ffff
    ..48: dw room_objlist_48, room_enemylist_48, $c102,     $ffff
    ..49: dw room_objlist_49, room_enemylist_49, $c102,     $ffff
    ..4a: dw room_objlist_4a, room_enemylist_4a, $c102,     $ffff
    ..4b: dw room_objlist_4b, room_enemylist_4b, $c102,     $ffff
    ..4c: dw room_objlist_4c, room_enemylist_4c, $c102,     $ffff
    ..4d: dw room_objlist_4d, room_enemylist_4d, $c102,     $ffff
    ..4e: dw room_objlist_4e, room_enemylist_4e, $c102,     $ffff
    ..4f: dw room_objlist_4f, room_enemylist_4f, $c102,     $ffff
    ..50: dw room_objlist_50, room_enemylist_50, $c203,     $ffff
    ..51: dw room_objlist_51, room_enemylist_51, $c003,     $ffff
    ..52: dw room_objlist_52, room_enemylist_52, $c103,     $ffff
    ..53: dw room_objlist_53, room_enemylist_53, $c102,     $ffff
    ..54: dw room_objlist_54, room_enemylist_54, $c102,     $ffff
    ..55: dw room_objlist_55, room_enemylist_55, $c102,     $ffff
    ..56: dw room_objlist_56, room_enemylist_56, $c102,     $ffff
    ..57: dw room_objlist_57, room_enemylist_57, $c102,     $ffff
    ..58: dw room_objlist_58, room_enemylist_58, $c102,     $ffff
    ..59: dw room_objlist_59, room_enemylist_59, $c102,     $ffff
    ..5a: dw room_objlist_5a, room_enemylist_5a, $c102,     $ffff
    ..5b: dw room_objlist_5b, room_enemylist_5b, $c102,     $ffff
    ..5c: dw room_objlist_5c, room_enemylist_5c, $c102,     $ffff
    ..5d: dw room_objlist_5d, room_enemylist_5d, $c102,     $ffff
    ..5e: dw room_objlist_5e, room_enemylist_5e, $c102,     $ffff
    ..5f: dw room_objlist_5f, room_enemylist_5f, $c102,     $ffff
             ;objs            enemies          bounds,bg;   special ptr
    ..60: dw room_objlist_60, room_enemylist_60, $c203,     $ffff
    ..61: dw room_objlist_61, room_enemylist_61, $c003,     $ffff
    ..62: dw room_objlist_62, room_enemylist_62, $c305,     $ffff
    ..63: dw room_objlist_63, room_enemylist_63, $c102,     $ffff
    ..64: dw room_objlist_64, room_enemylist_64, $c003,     $ffff
    ..65: dw room_objlist_65, room_enemylist_65, $c103,     $ffff
    ..66: dw room_objlist_66, room_enemylist_66, $c102,     $ffff
    ..67: dw room_objlist_67, room_enemylist_67, $c102,     $ffff
    ..68: dw room_objlist_68, room_enemylist_68, $c102,     $ffff
    ..69: dw room_objlist_69, room_enemylist_69, $c102,     $ffff
    ..6a: dw room_objlist_6a, room_enemylist_6a, $c102,     $ffff
    ..6b: dw room_objlist_6b, room_enemylist_6b, $c102,     $ffff
    ..6c: dw room_objlist_6c, room_enemylist_6c, $c102,     $ffff
    ..6d: dw room_objlist_6d, room_enemylist_6d, $c102,     $ffff
    ..6e: dw room_objlist_6e, room_enemylist_6e, $c102,     $ffff
    ..6f: dw room_objlist_6f, room_enemylist_6f, $c102,     $ffff
    ..70: dw room_objlist_70, room_enemylist_70, $c203,     $ffff
    ..71: dw room_objlist_71, room_enemylist_71, $c003,     $ffff
    ..72: dw room_objlist_72, room_enemylist_72, $c103,     $ffff
    ..73: dw room_objlist_73, room_enemylist_73, $c102,     $ffff
    ..74: dw room_objlist_74, room_enemylist_74, $c102,     $ffff
    ..75: dw room_objlist_75, room_enemylist_75, $c102,     $ffff
    ..76: dw room_objlist_76, room_enemylist_76, $c102,     $ffff
    ..77: dw room_objlist_77, room_enemylist_77, $c102,     $ffff
    ..78: dw room_objlist_78, room_enemylist_78, $c102,     $ffff
    ..79: dw room_objlist_79, room_enemylist_79, $c102,     $ffff
    ..7a: dw room_objlist_7a, room_enemylist_7a, $c102,     $ffff
    ..7b: dw room_objlist_7b, room_enemylist_7b, $c102,     $ffff
    ..7c: dw room_objlist_7c, room_enemylist_7c, $c102,     $ffff
    ..7d: dw room_objlist_7d, room_enemylist_7d, $c102,     $ffff
    ..7e: dw room_objlist_7e, room_enemylist_7e, $c102,     $ffff
    ..7f: dw room_objlist_7f, room_enemylist_7f, $c102,     $ffff
             ;objs            enemies          bounds,bg;   special ptr
    ..80: dw room_objlist_80, room_enemylist_80, $c203,     $ffff
    ..81: dw room_objlist_81, room_enemylist_81, $c002,     specialtilemaps_6&$7fff
    ..82: dw room_objlist_82, room_enemylist_82, $c005,     $ffff
    ..83: dw room_objlist_83, room_enemylist_83, $c006,     $ffff
    ..84: dw room_objlist_84, room_enemylist_84, $c006,     $ffff
    ..85: dw room_objlist_85, room_enemylist_85, $c106,     $ffff
    ..86: dw room_objlist_86, room_enemylist_86, $c106,     $ffff
    ..87: dw room_objlist_87, room_enemylist_87, $c106,     $ffff
    ..88: dw room_objlist_88, room_enemylist_88, $c106,     $ffff
    ..89: dw room_objlist_89, room_enemylist_89, $c106,     $ffff
    ..8a: dw room_objlist_8a, room_enemylist_8a, $c102,     $ffff
    ..8b: dw room_objlist_8b, room_enemylist_8b, $c102,     $ffff
    ..8c: dw room_objlist_8c, room_enemylist_8c, $c102,     $ffff
    ..8d: dw room_objlist_8d, room_enemylist_8d, $c102,     $ffff
    ..8e: dw room_objlist_8e, room_enemylist_8e, $c102,     $ffff
    ..8f: dw room_objlist_8f, room_enemylist_8f, $c102,     $ffff
    ..90: dw room_objlist_90, room_enemylist_90, $c203,     $ffff
    ..91: dw room_objlist_91, room_enemylist_91, $c003,     $ffff
    ..92: dw room_objlist_92, room_enemylist_92, $c103,     $ffff
    ..93: dw room_objlist_93, room_enemylist_93, $c102,     $ffff
    ..94: dw room_objlist_94, room_enemylist_94, $c102,     $ffff
    ..95: dw room_objlist_95, room_enemylist_95, $c102,     $ffff
    ..96: dw room_objlist_96, room_enemylist_96, $c102,     $ffff
    ..97: dw room_objlist_97, room_enemylist_97, $c102,     $ffff
    ..98: dw room_objlist_98, room_enemylist_98, $c102,     $ffff
    ..99: dw room_objlist_99, room_enemylist_99, $c102,     $ffff
    ..9a: dw room_objlist_9a, room_enemylist_9a, $c102,     $ffff
    ..9b: dw room_objlist_9b, room_enemylist_9b, $c102,     $ffff
    ..9c: dw room_objlist_9c, room_enemylist_9c, $c102,     $ffff
    ..9d: dw room_objlist_9d, room_enemylist_9d, $c102,     $ffff
    ..9e: dw room_objlist_9e, room_enemylist_9e, $c102,     $ffff
    ..9f: dw room_objlist_9f, room_enemylist_9f, $c102,     $ffff
             ;objs            enemies          bounds,bg;   special ptr
    ..a0: dw room_objlist_a0, room_enemylist_a0, $c203,     $ffff
    ..a1: dw room_objlist_a1, room_enemylist_a1, $c003,     $ffff
    ..a2: dw room_objlist_a2, room_enemylist_a2, $c005,     $ffff
    ..a3: dw room_objlist_a3, room_enemylist_a3, $c006,     $ffff
    ..a4: dw room_objlist_a4, room_enemylist_a4, $c006,     $ffff
    ..a5: dw room_objlist_a5, room_enemylist_a5, $c006,     $ffff
    ..a6: dw room_objlist_a6, room_enemylist_a6, $c006,     $ffff
    ..a7: dw room_objlist_a7, room_enemylist_a7, $c102,     $ffff
    ..a8: dw room_objlist_a8, room_enemylist_a8, $c102,     $ffff
    ..a9: dw room_objlist_a9, room_enemylist_a9, $c102,     $ffff
    ..aa: dw room_objlist_aa, room_enemylist_aa, $c102,     $ffff
    ..ab: dw room_objlist_ab, room_enemylist_ab, $c102,     $ffff
    ..ac: dw room_objlist_ac, room_enemylist_ac, $c102,     $ffff
    ..ad: dw room_objlist_ad, room_enemylist_ad, $c102,     $ffff
    ..ae: dw room_objlist_ae, room_enemylist_ae, $c102,     $ffff
    ..af: dw room_objlist_af, room_enemylist_af, $c102,     $ffff
    ..b0: dw room_objlist_b0, room_enemylist_b0, $c203,     $ffff
    ..b1: dw room_objlist_b1, room_enemylist_b1, $c003,     $ffff
    ..b2: dw room_objlist_b2, room_enemylist_b2, $c103,     $ffff
    ..b3: dw room_objlist_b3, room_enemylist_b3, $c102,     $ffff
    ..b4: dw room_objlist_b4, room_enemylist_b4, $c203,     $ffff
    ..b5: dw room_objlist_b5, room_enemylist_b5, $c103,     $ffff
    ..b6: dw room_objlist_b6, room_enemylist_b6, $c102,     $ffff
    ..b7: dw room_objlist_b7, room_enemylist_b7, $c102,     $ffff
    ..b8: dw room_objlist_b8, room_enemylist_b8, $c102,     $ffff
    ..b9: dw room_objlist_b9, room_enemylist_b9, $c102,     $ffff
    ..ba: dw room_objlist_ba, room_enemylist_ba, $c102,     $ffff
    ..bb: dw room_objlist_bb, room_enemylist_bb, $c102,     $ffff
    ..bc: dw room_objlist_bc, room_enemylist_bc, $c102,     $ffff
    ..bd: dw room_objlist_bd, room_enemylist_bd, $c102,     $ffff
    ..be: dw room_objlist_be, room_enemylist_be, $c102,     $ffff
    ..bf: dw room_objlist_bf, room_enemylist_bf, $c102,     $ffff
    
             ;objs            enemies          bounds,bg;   special ptr
    ..c0: dw room_objlist_c0, room_enemylist_c0, $c203,     $ffff
    ..c1: dw room_objlist_c1, room_enemylist_c1, $c003,     $ffff
    ..c2: dw room_objlist_c2, room_enemylist_c2, $c005,     $ffff
    ..c3: dw room_objlist_c3, room_enemylist_c3, $c006,     $ffff
    ..c4: dw room_objlist_c4, room_enemylist_c4, $c006,     $ffff
    ..c5: dw room_objlist_c5, room_enemylist_c5, $c006,     $ffff
    ..c6: dw room_objlist_c6, room_enemylist_c6, $c006,     $ffff
    ..c7: dw room_objlist_c7, room_enemylist_c7, $c102,     $ffff
    ..c8: dw room_objlist_c8, room_enemylist_c8, $c102,     $ffff
    ..c9: dw room_objlist_c9, room_enemylist_c9, $c102,     $ffff
    ..ca: dw room_objlist_ca, room_enemylist_ca, $c102,     $ffff
    ..cb: dw room_objlist_cb, room_enemylist_cb, $c102,     $ffff
    ..cc: dw room_objlist_cc, room_enemylist_cc, $c102,     $ffff
    ..cd: dw room_objlist_cd, room_enemylist_cd, $c102,     $ffff
    ..ce: dw room_objlist_ce, room_enemylist_ce, $c102,     $ffff
    ..cf: dw room_objlist_cf, room_enemylist_cf, $c102,     $ffff
    ..d0: dw room_objlist_d0, room_enemylist_d0, $c203,     $ffff
    ..d1: dw room_objlist_d1, room_enemylist_d1, $c003,     $ffff
    ..d2: dw room_objlist_d2, room_enemylist_d2, $c103,     $ffff
    ..d3: dw room_objlist_d3, room_enemylist_d3, $c203,     roomroutines_precat         ;precat
    ..d4: dw room_objlist_d4, room_enemylist_d4, $c103,     $ffff                       ;cat
    ..d5: dw room_objlist_d5, room_enemylist_d5, $e308,     specialtilemaps_1&$7fff     ;ending scene
    ..d6: dw room_objlist_d6, room_enemylist_d6, $e308,     specialtilemaps_2&$7fff     ;
    ..d7: dw room_objlist_d7, room_enemylist_d7, $e308,     specialtilemaps_3&$7fff     ;
    ..d8: dw room_objlist_d8, room_enemylist_d8, $e308,     specialtilemaps_4&$7fff     ;
    ..d9: dw room_objlist_d9, room_enemylist_d9, $e308,     specialtilemaps_5&$7fff     ;
    ..da: dw room_objlist_da, room_enemylist_da, $c102,     $ffff
    ..db: dw room_objlist_db, room_enemylist_db, $c102,     $ffff
    ..dc: dw room_objlist_dc, room_enemylist_dc, $c102,     $ffff
    ..dd: dw room_objlist_dd, room_enemylist_dd, $c102,     $ffff
    ..de: dw room_objlist_de, room_enemylist_de, $c102,     $ffff
    ..df: dw room_objlist_df, room_enemylist_df, $c102,     $ffff
    
             ;objs            enemies          bounds,bg;   special ptr
    ..e0: dw room_objlist_e0, room_enemylist_e0, $c203,     $ffff
    ..e1: dw room_objlist_e1, room_enemylist_e1, $c003,     $ffff
    ..e2: dw room_objlist_e2, room_enemylist_e2, $c005,     $ffff
    ..e3: dw room_objlist_e3, room_enemylist_e3, $c006,     $ffff
    ..e4: dw room_objlist_e4, room_enemylist_e4, $c006,     $ffff
    ..e5: dw room_objlist_e5, room_enemylist_e5, $c006,     $ffff
    ..e6: dw room_objlist_e6, room_enemylist_e6, $c006,     $ffff
    ..e7: dw room_objlist_e7, room_enemylist_e7, $c102,     $ffff
    ..e8: dw room_objlist_e8, room_enemylist_e8, $c102,     $ffff
    ..e9: dw room_objlist_e9, room_enemylist_e9, $c102,     $ffff
    ..ea: dw room_objlist_ea, room_enemylist_ea, $c102,     $ffff
    ..eb: dw room_objlist_eb, room_enemylist_eb, $c102,     $ffff
    ..ec: dw room_objlist_ec, room_enemylist_ec, $c102,     $ffff
    ..ed: dw room_objlist_ed, room_enemylist_ed, $c102,     $ffff
    ..ee: dw room_objlist_ee, room_enemylist_ee, $c102,     $ffff
    ..ef: dw room_objlist_ef, room_enemylist_ef, $c102,     $ffff
    ..f0: dw room_objlist_f0, room_enemylist_f0, $c203,     $ffff
    ..f1: dw room_objlist_f1, room_enemylist_f1, $c003,     $ffff
    ..f2: dw room_objlist_f2, room_enemylist_f2, $c103,     $ffff
    ..f3: dw room_objlist_f3, room_enemylist_f3, $c102,     $ffff
    ..f4: dw room_objlist_f4, room_enemylist_f4, $c102,     $ffff
    ..f5: dw room_objlist_f5, room_enemylist_f5, $c102,     $ffff
    ..f6: dw room_objlist_f6, room_enemylist_f6, $c102,     $ffff
    ..f7: dw room_objlist_f7, room_enemylist_f7, $c102,     $ffff
    ..f8: dw room_objlist_f8, room_enemylist_f8, $c102,     $ffff
    ..f9: dw room_objlist_f9, room_enemylist_f9, $c102,     $ffff
    ..fa: dw room_objlist_fa, room_enemylist_fa, $c102,     $ffff
    ..fb: dw room_objlist_fb, room_enemylist_fb, $e102,     $ffff
    ..fc: dw room_objlist_fc, room_enemylist_fc, $e102,     $ffff
    ..fd: dw room_objlist_fd, room_enemylist_fd, $e102,     $ffff
    ..fe: dw room_objlist_fe, room_enemylist_fe, $e102,     $ffff
    ..ff: dw room_objlist_ff, room_enemylist_ff, $c003,     specialtilemaps_7&$7fff
    
    ..title: dw $0000, room_enemylist_title, $0000, $ffff
}

